import { useState } from 'react';
import { Check, ChevronDown, Database, X } from 'lucide-react';
import { SectionLabel } from '../ui/SectionLabel';

export function Evidence() {
  const [expanded, setExpanded] = useState(false);
  const sources = [{ title: 'Financiero', items: ['Historial crediticio BCRA', 'Exposición de deuda actual', 'Historial de mora'], tone: 'navy' }, { title: 'Producción', items: ['Historial de rendimiento regional', 'Tipo de cultivo', 'Área productiva'], tone: 'green' }, { title: 'Ambiente', items: ['Lluvia histórica', 'Frecuencia de sequía', 'Características del suelo', 'Estabilidad de vegetación'], tone: 'amber' }];
  return <section className="card evidence-card"><div className="card-header"><div><SectionLabel>TRAZABILIDAD DE DATOS</SectionLabel><h2>Evidencia de evaluación</h2></div><span className="demo-label"><Database size={12} /> DATOS DE DEMO</span></div><div className="evidence-columns">{sources.map((source) => <div key={source.title}><strong className={`evidence-title evidence-${source.tone}`}>{source.title}</strong>{source.items.map((item) => <span key={item}><Check size={13} />{item}</span>)}</div>)}</div><div className="evidence-foot"><span>La lluvia histórica se valida contra Open-Meteo; el resto de las fuentes son simuladas para esta demo.</span><button onClick={() => setExpanded((value) => !value)}>{expanded ? 'Ocultar diccionario de datos' : 'Ver diccionario de datos'} {expanded ? <X size={14} /> : <ChevronDown size={14} />}</button></div>{expanded && <div className="dictionary"><span><b>Dato</b><b>Proveedor</b><b>Actualización</b></span><span><em>Anomalía de lluvia</em><em><a href="https://open-meteo.com/en/docs/historical-weather-api" target="_blank" rel="noreferrer">Open-Meteo · dato real</a></em><em>Diario</em></span><span><em>Perfil de suelo</em><em>SoilGrids · simulado</em><em>Estático</em></span></div>}</section>;
}
