import { useMemo, useState } from 'react';
import { BarChart3, Bell, ChevronDown, CircleHelp, Database, FileText, LayoutDashboard, LineChart, Settings2, SlidersHorizontal, TrendingUp } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { demoCase, historicalYield, scenarios } from './data/demoCase';
import { FieldMap } from './components/map/FieldMap';
import { CreditDecision } from './components/underwriting/CreditDecision';
import { ScoreSummary } from './components/underwriting/ScoreSummary';
import { StressTest } from './components/stress/StressTest';
import { ContinuousUnderwriting } from './components/monitoring/ContinuousUnderwriting';
import { SectionLabel } from './components/ui/SectionLabel';
import type { ScenarioKey } from './types/underwriting';

function MetricGroup({ title, tone, items }: { title: string; tone: string; items: Array<{ label: string; value: string; badge?: string }> }) {
  return <div className="metric-group"><div className={`metric-group-title ${tone}`}><span />{title}</div>{items.map((item) => <div className="metric-row" key={item.label}><span>{item.label}</span><strong>{item.value} {item.badge && <em className={`badge badge-${item.badge === 'Medium' ? 'amber' : 'green'}`}>{item.badge}</em>}</strong></div>)}</div>;
}

function Explainability() {
  const contributions = [{ label: 'Productive stability', value: 14, type: 'positive' }, { label: 'Soil & water conditions', value: 11, type: 'positive' }, { label: 'Historical yield', value: 8, type: 'positive' }, { label: 'Vegetation stability', value: 7, type: 'positive' }, { label: 'Climate resilience', value: 6, type: 'positive' }, { label: 'Financial leverage', value: -9, type: 'negative' }, { label: 'Historical delinquency', value: -5, type: 'negative' }, { label: 'Yield volatility', value: -3, type: 'negative' }];
  return <section className="card explain-card"><div className="card-header"><div><SectionLabel>DECISION LOGIC</SectionLabel><h2>WHY 82?</h2></div><span className="rule-tag">RULE-BASED</span></div><div className="explain-body"><div className="contribution-chart">{contributions.map((contribution) => <div className="contribution" key={contribution.label}><div className="contribution-bar"><i className={contribution.type} style={{ height: `${Math.abs(contribution.value) / 14 * 100}%` }} /></div><strong className={contribution.type}>{contribution.value > 0 ? '+' : ''}{contribution.value}</strong><span>{contribution.label}</span></div>)}</div><div className="capacity-bars"><div><span>Financial capacity <b>61</b></span><div className="capacity-track"><i className="amber-fill" style={{ width: '61%' }} /></div></div><div><span>Productive capacity <b>87</b></span><div className="capacity-track"><i className="green-fill" style={{ width: '87%' }} /></div></div><p>Productive capacity partially offsets a weaker financial profile.</p></div></div></section>;
}

function HistoricalChart() {
  return <section className="card history-card"><div className="card-header"><div><SectionLabel>PRODUCTION RECORD</SectionLabel><h2>Historical yield</h2></div><div className="history-score"><span>Stability</span><strong>82</strong><small>/ 100</small></div></div><div className="chart-legend"><span><i className="legend-green" /> Yield · tn/ha</span><span><i className="legend-amber" /> Drought year</span></div><div className="history-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={historicalYield} margin={{ top: 8, right: 8, left: -18, bottom: 0 }}><defs><linearGradient id="yieldFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#79a85b" stopOpacity={0.3} /><stop offset="100%" stopColor="#79a85b" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e5e8e2" /><XAxis dataKey="year" tick={{ fontSize: 10, fill: '#8a918c' }} axisLine={false} tickLine={false} /><YAxis domain={[4, 10]} tick={{ fontSize: 10, fill: '#8a918c' }} axisLine={false} tickLine={false} tickFormatter={(value) => `${value}`} /><Tooltip contentStyle={{ border: '1px solid #dfe4dc', borderRadius: 8, fontSize: 12 }} formatter={(value) => [`${value} tn/ha`, 'Yield']} /><ReferenceLine y={6.5} stroke="#d6a14d" strokeDasharray="3 3" /><Area type="monotone" dataKey="yield" stroke="#4e814f" strokeWidth={2.5} fill="url(#yieldFill)" dot={(props) => { const { cx, cy, payload } = props; return <circle cx={cx} cy={cy} r={payload.drought ? 4 : 3} fill={payload.drought ? '#d6a14d' : '#4e814f'} stroke="#fff" strokeWidth={2} />; }} /></AreaChart></ResponsiveContainer></div></section>;
}

function Evidence() {
  return <section className="card evidence-card"><div className="card-header"><div><SectionLabel>DATA TRACEABILITY</SectionLabel><h2>Underwriting evidence</h2></div><span className="demo-label"><Database size={12} /> DEMO DATASET</span></div><div className="evidence-columns"><div><strong>Financial</strong><span>✓ BCRA credit history</span><span>✓ Current debt exposure</span><span>✓ Delinquency history</span></div><div><strong>Production</strong><span>✓ Regional yield history</span><span>✓ Crop type</span><span>✓ Productive area</span></div><div><strong>Environment</strong><span>✓ Historical rainfall</span><span>✓ Drought frequency</span><span>✓ Soil characteristics</span><span>✓ Vegetation stability</span></div></div><div className="evidence-foot"><span>Sources are simulated for this product demo.</span><button>View data dictionary <ChevronDown size={14} /></button></div></section>;
}

function App() {
  const [scenarioKey, setScenarioKey] = useState<ScenarioKey>('base');
  const scenario = useMemo(() => scenarios.find((item) => item.key === scenarioKey) ?? scenarios[0], [scenarioKey]);
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">A<span>•</span></div><div><strong>AGRO<span>SCORE</span></strong><small>PRODUCTIVE CREDIT INTELLIGENCE</small></div></div><div className="sidebar-case"><span>ACTIVE CASE</span><strong>Marcos Juárez</strong><small>Córdoba · 30-71284539-9</small><div className="case-status"><i /> Underwriting in review</div></div><nav><div className="nav-section">WORKSPACE</div><a className="active"><LayoutDashboard size={17} />Overview</a><a><BarChart3 size={17} />Portfolio <span className="nav-count">4</span></a><a><LineChart size={17} />Monitoring</a><div className="nav-section nav-spaced">TOOLS</div><a><FileText size={17} />Evidence library</a><a><SlidersHorizontal size={17} />Scenario builder</a><a><Settings2 size={17} />Settings</a></nav><div className="sidebar-footer"><button><CircleHelp size={15} />Product guide</button><div className="user-row"><div className="avatar">JD</div><div><strong>Julián Díaz</strong><span>Risk analyst</span></div><ChevronDown size={14} /></div></div></aside>
    <main className="main-content"><header className="top-header"><div><span className="breadcrumb">WORKSPACE <b>/</b> UNDERWRITING CASE</span><h1>Productive risk assessment</h1></div><div className="header-actions"><button className="icon-btn notification"><Bell size={17} /><i /></button><div className="demo-case"><span>DEMO CASE</span><strong>Marcos Juárez, Córdoba <ChevronDown size={14} /></strong></div></div></header>
      <div className="content-wrap"><div className="hero-grid"><FieldMap scenario={scenario} /><div className="summary-column"><ScoreSummary caseData={demoCase} scenario={scenario} /><CreditDecision caseData={demoCase} scenario={scenario} /></div></div>
        <div className="metrics-strip"><div className="metrics-heading"><SectionLabel>OPERATIONAL PROFILE</SectionLabel><span>2026/27 campaign</span></div><MetricGroup title="PRODUCTION" tone="green" items={[{ label: 'Expected yield', value: `${scenario.yield.toFixed(1)} tn/ha` }, { label: 'Stress yield', value: '5.9 tn/ha' }, { label: 'Yield volatility', value: '18%' }]} /><MetricGroup title="CLIMATE" tone="blue" items={[{ label: 'Historical rainfall', value: '645 mm' }, { label: 'Current anomaly', value: '−12%' }, { label: 'Drought risk', value: 'Medium', badge: 'Medium' }]} /><MetricGroup title="SOIL" tone="brown" items={[{ label: 'Soil quality', value: '89 / 100' }, { label: 'Organic carbon', value: '2.1%' }, { label: 'Soil pH', value: '6.2' }]} /></div>
        <div className="lower-grid"><div className="left-stack"><Explainability /><StressTest selected={scenarioKey} scenarios={scenarios} onChange={setScenarioKey} /><HistoricalChart /></div><div className="right-stack"><section className="insight-card"><div className="insight-head"><div className="insight-symbol">✦</div><div><SectionLabel>UNDERWRITING INSIGHT</SectionLabel><span>Decision support · Demo case</span></div></div><p>Moderate financial risk is partially offset by strong productive resilience. Historical yield stability and favorable soil characteristics support the operation, but the requested ARS 100M exposure becomes vulnerable under a severe drought scenario. Recommended initial exposure: <strong>ARS 76M.</strong></p><button>View evidence <TrendingUp size={14} /></button></section><Evidence /></div></div><ContinuousUnderwriting /><footer className="footer"><span>AGROSCORE v0.1 · Mock-first underwriting environment</span><span>All scores are decision-support indicators, not probability of default.</span></footer></div>
    </main>
  </div>;
}

export default App;
